<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
		<modelVersion>4.0.0</modelVersion>
		<groupId>br.com.loteria</groupId>
		<artifactId>loteria-parent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<packaging>pom</packaging>
		<modules>
			<module>loteria-common</module>
			<module>loteria-security</module>
			<module>loteria-lotofacil</module>
			<module>loteria-megasena</module>
			<module>loteria-api</module>
		</modules>

		<properties>
			<java.version>17</java.version>
			<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
			<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		</properties>

		<dependencyManagement>
			<dependencies>
				<dependency>
					<groupId>javax</groupId>
					<artifactId>javaee-api</artifactId>
					<version>8.0</version>
				</dependency>
				<dependency>
					<groupId>org.projectlombok</groupId>
					<artifactId>lombok</artifactId>
					<version>1.18.30</version>
				</dependency>
				<dependency>
					<groupId>io.swagger</groupId>
					<artifactId>swagger-annotations</artifactId>
					<version>1.6.11</version>
				</dependency>
				<dependency>
					<groupId>io.jsonwebtoken</groupId>
					<artifactId>jjwt-api</artifactId>
					<version>0.11.5</version>
				</dependency>
				<dependency>
					<groupId>io.jsonwebtoken</groupId>
					<artifactId>jjwt-impl</artifactId>
					<version>0.11.5</version>
				</dependency>
				<dependency>
					<groupId>io.jsonwebtoken</groupId>
					<artifactId>jjwt-jackson</artifactId>
					<version>0.11.5</version>
				</dependency>
				<dependency>
					<groupId>com.fasterxml.jackson.datatype</groupId>
					<artifactId>jackson-datatype-jsr310</artifactId>
					<version>2.15.2</version>
				</dependency>
				<dependency>
					<groupId>com.fasterxml.jackson.core</groupId>
					<artifactId>jackson-annotations</artifactId>
					<version>2.15.2</version>
				</dependency>
				<dependency>
					<groupId>org.hibernate</groupId>
					<artifactId>hibernate-core</artifactId>
					<version>5.6.15.Final</version>
				</dependency>
				<dependency>
					<groupId>mysql</groupId>
					<artifactId>mysql-connector-java</artifactId>
					<version>8.0.33</version>
				</dependency>
				<dependency>
					<groupId>io.swagger</groupId>
					<artifactId>swagger-jaxrs</artifactId>
					<version>1.6.11</version>
				</dependency>
				<dependency>
					<groupId>io.swagger</groupId>
					<artifactId>swagger-models</artifactId>
					<version>1.6.11</version>
				</dependency>
				<dependency>
					<groupId>org.webjars</groupId>
					<artifactId>swagger-ui</artifactId>
					<version>3.52.5</version>
				</dependency>
				<dependency>
					<groupId>com.google.guava</groupId>
					<artifactId>guava</artifactId>
					<version>20.0</version>
				</dependency>
				<dependency>
					<groupId>junit</groupId>
					<artifactId>junit</artifactId>
					<version>4.13.2</version>
				</dependency>
				<dependency>
					<groupId>org.mockito</groupId>
					<artifactId>mockito-core</artifactId>
					<version>3.12.4</version>
				</dependency>
			</dependencies>
		</dependencyManagement>

		<build>
			<pluginManagement>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-compiler-plugin</artifactId>
						<version>3.11.0</version>
						<configuration>
							<annotationProcessorPaths>
								<path>
									<groupId>org.projectlombok</groupId>
									<artifactId>lombok</artifactId>
									<version>1.18.30</version>
								</path>
							</annotationProcessorPaths>
							<encoding>UTF-8</encoding>
						<release>${java.version}</release>
						</configuration>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-resources-plugin</artifactId>
						<version>3.3.0</version>
						<configuration>
							<encoding>UTF-8</encoding>
						</configuration>
					</plugin>
				</plugins>
			</pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
				</plugin>
			</plugins>
		</build>
	</project>
